# Generated by Django 5.2.5 on 2025-08-24 11:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
