# Generated by Django 5.2.5 on 2025-08-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_accepted',
            new_name='accepted',
        ),
    ]
